package com.myprojects.qrscanner.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Data model representing a QR code scan entry in the local database.
 * 
 * This entity class defines the structure for storing scanned QR code data
 * in the Room database. Each scan contains the QR code content, a unique ID,
 * and a timestamp of when the scan occurred.
 * 
 * @property id The unique identifier for this scan entry. Auto-generated by Room.
 * @property content The text content extracted from the scanned QR code.
 * @property timestamp The timestamp when the scan was performed, in milliseconds since epoch.
 * 
 * @author Edouard Makon
 * @since 1.0
 */
@Entity(tableName = "scans")
data class Scan(
    /**
     * Primary key for the scan entry. Auto-generated by Room database.
     * Defaults to 0, which will be replaced with the actual ID when inserted.
     */
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    
    /**
     * The text content extracted from the scanned QR code.
     * This can be any string that was encoded in the QR code (URL, text, etc.).
     */
    val content: String,
    
    /**
     * The timestamp when this scan was performed.
     * Stored as milliseconds since epoch (January 1, 1970 UTC).
     * Defaults to the current system time when the object is created.
     */
    val timestamp: Long = System.currentTimeMillis()
)