name: QR Scanner CI/CD

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'app/src/**'
      - 'app/build.gradle.kts'
      - 'gradle.properties'
      - 'app/src/main/AndroidManifest.xml'
      - '.github/workflows/**'

  pull_request:
    branches: [ main, master ]
    paths:
      - 'app/src/**'
      - 'app/build.gradle.kts'
      - 'gradle.properties'
      - 'app/src/main/AndroidManifest.xml'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test and Lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Run linting
        run: ./gradlew lint
        continue-on-error: true

      - name: Show lint results
        run: |
          echo "=== Lint Results ==="
          if [ -f "app/build/reports/lint-results.xml" ]; then
            echo "XML report found"
          fi
          if [ -f "app/build/reports/lint-results.html" ]; then
            echo "HTML report found"
          fi
          if [ -d "app/build/reports/lint-results" ]; then
            echo "Lint results directory found"
            ls -la app/build/reports/lint-results/
          fi
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: app/build/reports/tests/
          retention-days: 7

      - name: Upload lint results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-results
          path: |
            app/build/reports/lint-results.xml
            app/build/reports/lint-results.html
            app/build/reports/lint-results/
          retention-days: 7

  build:
    runs-on: ubuntu-latest
    name: Build APK
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: qr-scanner-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: qr-scanner-release
          path: app/build/outputs/apk/release/app-release.apk
          retention-days: 30

  security:
    runs-on: ubuntu-latest
    name: Security Check
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run dependency check
        run: ./gradlew dependencyCheckAnalyze
        continue-on-error: true

      - name: Upload security report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-report
          path: |
            app/build/reports/dependency-check-report.html
            app/build/reports/dependency-check-report.xml
            app/build/reports/
          retention-days: 7
